### ISSUE TITLE
contentFor doesn't work

### ISSUE THREAD

**Issue by marcemira** [unwiredbrain/ember-cli-piwik#1]
Hello, I just installed and configured this addon, very awesome one ;)

But it seems like it's not rendering nothing to any content-for. I have the {{content-for 'head-footer'}} and 
{{content-for 'body-footer'}} in my index.html, but nothing seems to change. I also have a " _paq is not defined" error in the console since it won't finde the piwik script. Any ideas? I'm on cli 0.2.3.

Thanks!

**Comment by unwiredbrain** [comment]
Hi @marcemira 

Two points:
1. did you add your Piwik configuration in `config/environment.js`?
2. did you change your CSP settings in `config/environment.js`?

**Comment by marcemira** [comment]
Hello @unwiredbrain, I'm sorry, my mistake. I accidentally left a bad config that nullified the ENV.piwik.sid/url. But I have another issue that I'm about to report
