### ISSUE TITLE
Do not track loading substate

### ISSUE THREAD

**Issue by jhass** [unwiredbrain/ember-cli-piwik#3]
At least an option to skip it would be great, talking about the Router mixin here. Or maybe even just a general configurable blacklist would be a good addition.

**Comment by unwiredbrain** [comment]
I built a simple app with a slow resource but I can't manage to track a loading substate, can you tell me how to replicate?

Can you post your Router configuration, please?

How are you using your substates? Routes? Templates?

**Comment by jhass** [comment]
https://github.com/jhass/carc.in/blob/master/frontend/app/router.js#L9

I'm very new to Ember, so I guess I do wrong by manually transitioning into the `loading` substate in this instance https://github.com/jhass/carc.in/blob/master/frontend/app/controllers/run_request.js#L27

**Comment by unwiredbrain** [comment]
I don't think you should transition directly into the `loading` substate, that should be handled automagically by the router when a resource is taking too long to load.

Take a look at the [Ember guides](http://guides.emberjs.com/v1.12.0/routing/loading-and-error-substates/)

**Comment by jhass** [comment]
Well, though I'm still pretty blank on how to solve this differently, it's the `model.save` call that may take a long time in my case, not loading some model.

And in any case I still think the general blacklist would be a valid feature :)

**Comment by unwiredbrain** [comment]
Blacklist: maybe, but do you have a valid use case?

To be clear: I'm not against it, I just want to find a good use case to justify it ;)

**Comment by jhass** [comment]
Uh, well since my usecase is considered invalid... I could imagine some applications having tokens in the URLs that shouldn't be tracked or something like that. Or pages used to display a message for some time before loading the next route automatically etc.

**Comment by unwiredbrain** [comment]
You mean URL params with “tokens in the URLs that shouldn't be tracked or something like that” or specific URLs on their own?

**Comment by jhass** [comment]
Well, both. I guess one implementation could be to just provide a callback hook where everyone can implement their own logic, "callback returns false" -> "do not track".

**Comment by unwiredbrain** [comment]
I'm not sure I get what you mean…

How would you provide the callback hook? Where? When?

**Comment by jhass** [comment]
I guess I'm not able to make myself clear here. My usecase is denied, I can't find an alternative to it anywhere, which might just be lack of experience with Ember. And me pulling out usecases out of my ass that I don't have won't get us anywhere.

If you don't see that some general way to filter what's being tracked is useful, then that's your decision as maintainer.

**Comment by unwiredbrain** [comment]
Anyway, I think you're misusing the `loading` substate, as (the way I understood it) you're not meant to transition into it directly _ever_, it's something that should happen automatically when things take too long.

That being said, I guess you can still define an `app/templates/run_request/loading.hbs` template and get the same functionality. Better test it properly though… (And always keep an eye on the guides.)

Apart from that, defining a blacklist should be fairly easy to implement and test. Can you open another issue please, more specific?
